src/ws.cpp

This header is not apparently necessary, and it is not present in non-mesa SDKs.

Remove unnecessary include EGL/eglmesaext.h

---

src/linux-dmabuf/drm_fourcc.h

Inside flatpak on aarch64 I am getting the following build failure:
```
In file included from /home/thiblahute/devel/Webkit/webkit-master/WebKitBuild/FlatpakCache/WPEBackend-fdo/src/linux-dmabuf/linux-dmabuf.h:15:0,
from /home/thiblahute/devel/Webkit/webkit-master/WebKitBuild/FlatpakCache/WPEBackend-fdo/src/view-backend-exportable-fdo-egl.cpp:26:
/home/thiblahute/devel/Webkit/webkit-master/WebKitBuild/FlatpakCache/WPEBackend-fdo/src/linux-dmabuf/drm_fourcc.h:30:15: error: conflicting declaration ‘typedef long long unsigned int uint64_t’
#define __u64 uint64_t
^
In file included from /usr/lib/gcc/aarch64-unknown-linux/6.2.0/include/stdint.h:9:0,
from /home/thiblahute/devel/Webkit/webkit-master/WebKitBuild/FlatpakCache/WPEBackend-fdo/src/linux-dmabuf/linux-dmabuf.h:13,
from …
```

Stop defining __u32 and __u64 as it might already be typedefed

---

CMakeLists.txt
cmake/VersioningUtils.cmake

This is needed in preparation for the 1.0.0 release.
VersioningUtils.cmake is imported from the WebKit source tree:
https://trac.webkit.org/browser/webkit/trunk/Source/cmake/VersioningUtils.cmake
----
Related: https://github.com/WebPlatformForEmbedded/WPEBackend/pull/26

Use the libtool versioning scheme for libWPEBackend-fdo

---

NEWS
include/wpe-fdo/view-backend-exportable-egl.h
include/wpe-fdo/view-backend-exportable.h
src/view-backend-exportable-fdo-egl.cpp
src/view-backend-exportable-fdo.cpp

The client structs are used vtables, which in shouldn't change, so the parameters to the `*_create()` functions can be marked `const`.

Mark client struct parameters as const in _create() functions

---

src/interfaces.h

The `<wpe-egl.h>` inclusion should take care itself of bringing in any other headers it may need. Indeed, including `<wpe.h>` is not needed after WebPlatformForEmbedded/libwpe#34 has been merged.

Remove unneeded inclusion of the <wpe.h> header

---

src/view-backend-exportable-private.cpp

After calling wl_callback_send_done(), the callback wl_resource object
must be destroyed. This effectively avoids leaking these objects.

Clean up wl_callback resource in ViewBackend::dispatchFrameCallback()

---

src/ws.cpp

string.h is needed for strlen() and strstr().

ws: Fix build

---

CMakeLists.txt
include/wpe-fdo/exported-image-egl.h
include/wpe-fdo/view-backend-exportable-egl.h
src/exported-image-egl.cpp
src/view-backend-exportable-fdo-egl-private.h
src/view-backend-exportable-fdo-egl.cpp
src/ws.cpp
src/ws.h

A new vfunc has been added to wpe_view_backend_exportable_fdo_egl_client
that receives a struct wpe_fdo_egl_exported_image. The image is
created associated to its buffer resource, and released when the buffer
is destroyed if the user released it back.

Add wpe_fdo_egl_exported_image struct to wrap the EGL image

---

include/wpe-fdo/initialize-egl.h

It includes eglplatform that cand end up including Xlib.h.

Do not include egl.h in public headers

---

cmake/FindWaylandScanner.cmake

This improves `FindWaylandScanner.cmake` to allow it to find the `wayland-scanner` tool in any of the following ways (in order of preference):
1. By passing `-DWAYLAND_SCANNER=path/to/wayland-scanner` to CMake.
2. Looking for wayland-scanner in the current `$PATH`.
3. Figuring out the location from `pkg-config` (as before).
This will make the package friendlier to cross-compilation, and then build systems can either prepend their locations for host tools to `$PATH` (covered by 2. above), or they can specify the tool path in the command line (covered by 1. above) if they need to be more specific.
The motivation for this patch is to avoid kludges like the following:
https://patchwork.ozlabs.org/comment/2172010/

Improve how CMake looks for wayland-scanner

---

CMakeLists.txt
src/ipc-messages.h
src/ipc.cpp
src/ipc.h
src/renderer-backend-egl.cpp
src/view-backend-exportable-private.cpp
src/view-backend-exportable-private.h
src/ws.cpp
src/ws.h

The client can remove a target and create a new one for the same view
backend. In that case we need to unregister the current view backend in
the wayland compositor before registering the one. This patch renames
WS::Instance::createSurface as registerSurface to clarify that it's not
creating a new surface but registering a new one for the given id. Also
ViewBackend::m_id has been renamed as m_surfaceId to clarify that's not
the backend identifier, but the current surface identifier.

Handle the case of new target created for the same view backend

---

src/view-backend-exportable-fdo-egl.cpp
src/ws.cpp

1) compiler warning fix, changes the target type in the fourcc_mod_code macro to uint64_t. Replicates https://gitlab.freedesktop.org/mesa/drm/commit/b3c4c79e16f13a72e8124f69453a37135329f968.
2) One step to avoiding early releases of dmabuf-related wl_resources that can then cause tearing. If not nulled out here (like it's done for basic wl_resources), then the early release happens as soon as the next buffer is attached (see the attach implementation).

linux-dmabuf fixes

---

CMakeLists.txt
include/wpe-fdo/fdo.h
include/wpe-fdo/version.h.cmake

Adds macros `WPE_FDO_{MAJOR,MINOR,MICRO}_VERSION` with the version numbers and a `WPE_FDO_CHECK_VERSION()` macro, which can be used for conditional compilation.
Closes #46

Provide header versioning macros

---

include/wpe-fdo/fdo.h

<wpe/version.h> is also a libwpe header, so to avoid an include conflict, use a
quoted include instead of a bracket include.

fdo.h: Include local version.h header

---

src/ws.cpp

Renaming of the egl... members as s_ avoiding identifiers in our code
clashing with official names of functions is definitely a good idea to
avoid redeclaration errors like this:
```
src/ws.cpp:74:33: error: 'void* (* eglCreateImageKHR)(EGLDisplay,
EGLContext, EGLenum, EGLClientBuffer, const EGLint*)' redeclared as
different kind of symbol
static PFNEGLCREATEIMAGEKHRPROC eglCreateImageKHR;
```
The argument to eglGetProcAddress() has nothing to do with the name of
the variable. It is the name of a symbol from the EGL API:
<https://www.khronos.org/registry/EGL/sdk/docs/man/html/eglGetProcAddress.xhtml>.
Also added non-null asserts to those pointers to make more evident
crashes due to null in the future (for example: changes in the name of
the symbols):
```
assert(s_eglBindWaylandDisplayWL); …
```

Rename the EGL members

---

src/ws.cpp

It fixes the build on FreeBSD.
```
[11/16] Building CXX object CMakeFiles/WPEBackend-fdo.dir/src/ws.cpp.o
FAILED: CMakeFiles/WPEBackend-fdo.dir/src/ws.cpp.o 
/usr/bin/clang++  -B/home/lantw44/.local/bin  -DWAYLAND_1_10_OR_GREATER -DWPEBackend_fdo_EXPORTS -DWPE_FDO_COMPILATION -D_THREAD_SAFE -I../include -I. -I../src -I/home/lantw44/gnome/devinstall/include/glib-2.0 -I/home/lantw44/gnome/devinstall/lib/glib-2.0/include -I/home/lantw44/gnome/devinstall/include/wpe-1.0 -march=corei7 -B/home/lantw44/.local/bin -pipe -g3 -O0 -gz -fdebug-macro -std=c++11 -fno-exceptions -fno-rtti -fPIC   -pthread -MD -MT CMakeFiles/WPEBackend-fdo.dir/src/ws.cpp.o -MF CMakeFiles/WPEBackend-fdo.dir/src/ws.cpp.o.d -o CMakeFiles/WPEBackend-fdo.dir/src/ws.cpp.o -c ../src/ws.cpp
../src/ws.cpp:341:17: error: use of …
```

ws: Include stdio.h before using stderr

---

include/wpe-fdo/view-backend-exportable.h
src/view-backend-exportable-fdo.cpp

Add the export_dmabuf_resource callback to the
wpe_view_backend_exportable_fdo_client interface. This callback provides an
wpe_view_backend_exportable_fdo_dmabuf_resource object that describes the
linux-dmabuf resource that's being exported.
The originating wl_resource is included in this new descriptor struct in order
to enable the application to release the resource through the existing
wpe_view_backend_exportable_fdo_dispatch_release_buffer() API. Other members of
the descriptor struct provide all the available information about the dmabuf
to enable reusing it through various other APIs like libgbm.

Support linux-dmabuf exports in wpe_view_backend_exportable_fdo_client

---

include/wpe-fdo/view-backend-exportable.h
src/linux-dmabuf/linux-dmabuf.cpp
src/linux-dmabuf/linux-dmabuf.h

Convert back from int32_t to simply int when storing file descriptor values,
conforming to the usual Linux standards for this topic.

Use int as the file descriptor type

---

CMakeLists.txt
src/view-backend-exportable-private.h

The first commit arranges passing `-Wall` to the compiler, checking whether compiler flags are supported before adding them to the set of used ones, and using CMake's built-in C/C++ standard selection smarts. The second adds `final` to declarations to avoid a compiler warning (and it is good practice, too).

Arrange passing -Wall, check whether used compiler flags are supported

---

CMakeLists.txt
src/fdo.cpp
src/interfaces.h
src/renderer-backend-egl.cpp
src/renderer-host.cpp
src/ws-client.cpp
src/ws-client.h
src/ws.cpp

Move Wayland client logic into WS::BaseBackend, WS::BaseTarget classes

---

CMakeLists.txt
cmake/FindEGL.cmake

This modifies `FindEGL.cmake` to make it create the `GL::egl` imported library target, and using it from `CMakeLists.txt`; in the same vein as the changes recently done to `FindWPE.cmake`.
----
This goes in the same spirit as #59 :small_airplane:

cmake: Use an imported library for EGL

---

src/exported-image-egl.cpp
src/view-backend-exportable-fdo-egl-private.h
src/view-backend-exportable-fdo-egl.cpp
src/view-backend-exportable-fdo.cpp
src/view-backend-exportable-private.cpp
src/view-backend-exportable-private.h

This tries to do a better job of tracking wl_resource lifetime and managing the resource release process in cases where the wl_resource was already destroyed.

wl_resource management fixes

---

src/view-backend-exportable-fdo-egl.cpp
src/view-backend-exportable-fdo.cpp
src/view-backend-exportable-private.cpp
src/view-backend-exportable-private.h

* view-backend-exportable-private: some cleanups and renaming around frame callbacks.
* view-backend-exportable-private: improve frame callback wl_resource management
Use a destroy listener on frame callback resources in order to be able to
properly clean up in case the underlying client disappears.
Internal management of these resources in ViewBackend now uses wl_list.
* view-backend-exportable-fdo: improve buffer wl_resource management
Use a destroy handle on the buffer wl_resource in order to properly track the
resource's lifetime. In case the resource was destroyed while corresponding
wl_resource was exported to the client, the subsequent release should avoid
dispatching buffer release notification on the already-destroyed resource.
To achieve this, buffer resources are tracked inside …

wl_resource management fixes (#73)

---

cmake/FindEGL.cmake
cmake/FindWPE.cmake

Versions of CMake prior to 3.11 do not support using `target_link_libraries()` to setup `INTERFACE_LINK_LIBRARIES`. Using `set_property()` directly works in all 3.x versions, including 3.11 and newer.
Fixes #75

CMake: Avoid target_link_libraries() with imported targets

---

CMakeLists.txt
src/ws.cpp

Instead of checking the Wayland version with CMake, and then adding a preprocessor macro, check the `WAYLAND_VERSION_*` values directly. Those
are defined by the Wayland headers.

Simplify Wayland version check

---

CMakeLists.txt
src/ipc.cpp
src/ws-client.cpp
src/ws.cpp

This uses `g_warning(...)` instead of `fprintf(stderr, ...)`, and `g_error()`
instead of `std::abort()` so at least in case of fatal errors there will be a message that might be useful for developers before the process is terminated.
Additionally, sets `G_LOG_DOMAIN="WPE-FDO"` during compilation, so messages can be filtered i.e. using the `G_MESSAGES_DEBUG` environment variable.
Closes #67 and #68

Use GLib functions for logging

---

src/ws.cpp

In Fedora Rawhide, while trying to build WebKitGTK, I get a build error otherwise,
as `PFNEGLQUERYWAYLANDBUFFERWL` is defined in `eglmesaext.h`.
It looks like this header has existed for quite a while so should be fine to include
directly.

Add missing include.

---

CMakeLists.txt
include/wpe-fdo/extensions/video-plane-display-dmabuf.h
src/extensions/video-plane-display-dmabuf-receiver.cpp
src/extensions/video-plane-display-dmabuf.cpp
src/extensions/wpe-video-plane-display-dmabuf.xml
src/ws-client.cpp
src/ws-client.h
src/ws.cpp
src/ws.h

Introducing a new protocol enabling client-side video rendering. In WebKit
decoded video frames will be optionally exported to DMABuf fds and passed on
through the IPC wire using this protocol. On the other end, the browser (Cog for
instance) should receive all the informations needed so it can position and
render the video surfaces directly.
With contributions from Žan Doberšek <zdobersek@igalia.com>.

DMABuf video plane display protocol

---

CMakeLists.txt
include/wpe-fdo/exported-buffer-shm.h
include/wpe-fdo/fdo.h
include/wpe-fdo/view-backend-exportable-egl.h
include/wpe-fdo/view-backend-exportable.h
src/exported-buffer-shm-private.h
src/exported-buffer-shm.cpp
src/linux-dmabuf/linux-dmabuf.cpp
src/linux-dmabuf/linux-dmabuf.h
src/view-backend-exportable-fdo-egl.cpp
src/view-backend-exportable-fdo.cpp
src/view-backend-exportable-private.cpp
src/view-backend-exportable-private.h
src/ws.cpp
src/ws.h

Mainly:
* a small new API to chaperone the wl_shm_buffer object
* new export functions on the exportable interfaces
* wl_shm initialization
* optional EGL_wl_bind_wayland_display, in case the underlying GL library doesn't provide it when it's in software-rasterizer mode

shm support

---

src/ws.cpp

While building WebKit I came across with the build break of 1.4 release.
Digging the intertubes I found Archlinux reported the same issue and proposed this very same patch:
https://bugs.archlinux.org/task/64367
Also this header is already included in master, and this pull request is a cherry-pick of that commit.

ws: inlude eglmesaext.h

---

src/view-backend-exportable-fdo.cpp

This adds the missing <cstring> inclusion and the std:: namespace prefix
to the memset() invocation.

Fix usage of undeclared std::memset() function

---

src/extensions/video-plane-display-dmabuf.cpp

The videoPlaneDisplayDmaBuf pointer can remain NULL if no receiver was
registered on client-side, so it needs to be checked before usage.

video-plane-display-dmabuf: Check receiver before using it

---

src/ws.cpp

eglmesaext.h is not provided by all EGL implementations, but those
implementations typically provide the necessary definitions in eglext.h.
Add a configure time check to see if eglmesaext.h is present and include
it if so.

Remove eglmesaext.h

---

src/ws.cpp

Instruct `wl_display_get_event_loop()` to not block by passing zero as timeout, instead of letting it block indefinitely.
Fixes #94

ws: Do not block on wl_event_loop_dispatch()

---

CMakeLists.txt

CMake: Explicitly require libwpe 1.5.90 or newer

---

src/renderer-host.cpp

The wpe_renderer_host_exportable_fdo_initialize() entrypoint is
an older version of wpe_fdo_initialize_for_egl_display() and should
have been removed already. It's not exposed in any header and was
thus not usable through API.

Remove wpe_renderer_host_exportable_fdo_initialize()

---

CMakeLists.txt
src/linux-dmabuf/linux-dmabuf.cpp
src/view-backend-exportable-fdo-egl.cpp
src/view-backend-exportable-fdo.cpp
src/ws-egl.cpp
src/ws-egl.h
src/ws.cpp
src/ws.h

Have the WS::Instance class adopt an implementation object that extends
the WS::Instance::Impl interface. This would allow for different types
of implementations being instantiated on the Wayland IPC channel that's
managed by WS::Instance.
The current, EGL-oriented implementation is moved into the ImplEGL
class, and the existing interfaces are made to implicitly depend on
that implementation being used -- which still works since it's the
only implementation currently available. The integration of specific
export interfaces along with the viable implementations will be
improved once more implementations are added.

Provide impl facilities for WS::Instance

---

CMakeLists.txt
include/wpe-fdo/fdo-egl.h
include/wpe-fdo/fdo.h

Add the missing include directories to the HotDoc command and arrange headers to use local inclusion (with `""` instead of `<>`) to ensure that source tree files are picked first.

doc: Fix HotDoc warnings about missing headers

---

CMakeLists.txt
include/wpe-fdo/unstable/fdo-shm.h
include/wpe-fdo/unstable/initialize-shm.h
src/initialize-shm.cpp
src/ws-shm.cpp
src/ws-shm.h
src/ws.h

Add possibility of only enabling wl_shm protocol on the Wayland
display connection, effectively forcing Mesa-based Wayland-EGL
platform implementations to perform software-based rasterization.
In this case, the `export_shm_buffer` callbacks on relevant
interfaces would be invoked with the relevant wl_shm buffer data.

Provide SHM-only mode

---

.travis.yml
CMakeLists.txt
cmake/FindLibEpoxy.cmake
src/view-backend-exportable-fdo-egl.cpp
src/ws-egl.cpp
src/ws-egl.h

Instead of relying on EGL headers and library provided at compile-time,
use libepoxy to push that necessity to runtime.
The CMake integration follows the new 'imported' model. Instead of
manually parsing the EGL extension list to detect present extensions,
we can rely on the epoxy_has_egl_extension() function.

Use libepoxy for EGL operations

---

src/version.c

Otherwise client code relying on it will not compile (undefined reference to
`wpe_fdo_get_minor_version`, etc).

version: Expose version retrieval functions

---

.github/workflows/ci.yml
CMakeLists.txt
docs/index.markdown
meson.build
meson_options.txt
src/extensions/video-plane-display-dmabuf-receiver.cpp
src/extensions/video-plane-display-dmabuf.cpp
src/ipc.h
src/linux-dmabuf/linux-dmabuf.cpp
src/version.c
src/ws-client.h
src/ws.cpp
src/ws.h

I did this just as a proof of concept to see what it would take to migrate a CMake project to Meson, now that Buildroot has some support upstream for Meson — Feel free to skip merging this PR, or defer it for later, but personally I find Meson the less annoying of the existing configuration/build systems so my personal opinion is that this is a change for better :wink:

Add support for building using Meson

---

src/renderer-backend-egl.cpp

In the wpe_renderer_backend_egl_interface::get_native_display(),
explicitly cast the wl_display object to the EGLNativeDisplayType.
This should avoid compilation errors on rare EGL stacks that have
odd default EGLNativeDisplayType type definitions.

renderer-backend-egl: cast return value in get_native_display()

---

CMakeLists.txt
include/wpe/extensions/audio.h
meson.build
src/extensions/audio-receiver.cpp
src/extensions/audio.cpp
src/extensions/video-plane-display-dmabuf.cpp
src/extensions/wpe-audio.xml
src/ws.cpp
src/ws.h

Usually WebKit takes care of audio rendering by connecting to the default
audio system daemon such as PulseAudio or directly to ALSA. In some
situations the UI process might want to handle PCM samples itself.
To support this scenario, the UI process (created by GStreamer's wpesrc
element for instance) should register a #wpe_audio_receiver, implement its
callbacks and set the WebView audio-rendering-policy to
WEBKIT_AUDIO_RENDERING_POLICY_EXTERNAL.

Audio rendering protocol

---

CMakeLists.txt
include/wpe/unstable/fdo-eglstream.h
include/wpe/unstable/initialize-eglstream.h
include/wpe/unstable/view-backend-exportable-eglstream.h
meson.build
src/initialize-eglstream.cpp
src/view-backend-exportable-fdo-egl.cpp
src/view-backend-exportable-fdo-eglstream.cpp
src/view-backend-exportable-fdo.cpp
src/view-backend-exportable-private.cpp
src/view-backend-exportable-private.h
src/wayland-eglstream/wayland-eglstream-controller.xml
src/ws-eglstream.cpp
src/ws-eglstream.h
src/ws.h

Add initial support for the EGLStream buffer sharing mechanism that's
most prominently implemented in NVIDIA graphics stacks.
Existing integration of the EGLStream and the Wayland IPC mechanism
allows the client behavior to remain unchanged, meaning the Wayland
EGL platform can still be used. For this to work, we are required to
provide a `wl_eglstream_controller` object on the internal server.
This is done when `wpe_fdo_initialize_eglstream()` is invoked.
The resulting Wayland resources are exported to the user through the
new EGLStream-oriented interface, `wpe_view_backend_exportable_fdo_eglstream_client`.
`export_eglstream_producer_resource()` provides the wl_resource
object from which the user is required to extract the EGLStream
producer and immediately associate it with an EGLStream …

Provide EGLStream mode

---

include/wpe/extensions/audio.h
src/extensions/audio.cpp

To allow zero-copy packet handling the packet consumer needs to keep hold of the
packet_export until the audio data no longer needs to be accessed. In order to
support this, the producer side can now handle this through a release-notify
callback.
Fixes #120

extensions/audio: Add release-notify callback to the packet API

---

CMakeLists.txt

* `add_compile_definitions()` requires CMake 3.12, but Ubuntu-18.04 ships CMake 3.10. This fixes the build for old CMake versions.
* Noticed this on one of the packaging bots that [failed to build WPEBackend-fdo after updating it](https://build.webkit.org/builders/GTK-Linux-64bit-Release-Packaging-Nightly-Ubuntu1804/builds/58/steps/jhbuild/logs/stdio)

cmake: use add_definitions instead of add_compile_definitions

---

meson.build

Some drivers provide the `wl_egl_*` symbols their EGL library (either directly or indirectly in some other one needed by it) and do not ship a `wayland-egl` library. In that case, checking for `wayland-egl` fails even if the symbols are usable. To accomodate for this, check whether `wl_egl_create_window` is usable before trying to add the dependency on `wayland-egl`.
----
Idea from https://github.com/Igalia/cog/commit/170e3ef9d and also a patch proposed by @psaavedra (thanks!)

meson: Only add a wayland-egl dependency if needed

---

src/view-backend-exportable-fdo-egl.cpp
src/view-backend-exportable-fdo-eglstream.cpp
src/view-backend-exportable-fdo.cpp
src/view-backend-private.h

ClientBundle is created in exportable_fdo create functions but it's not
released when the wpe_view_backend_exportable_fdo struct is destroyed.
Direct leak of 40 byte(s) in 1 object(s) allocated from:
#0 0x7fe5b8aa6647 in operator new(unsigned long) (/lib/x86_64-linux-gnu/libasan.so.6+0xab647)
#1 0x7fe59ecd35d7 in wpe_view_backend_exportable_fdo_egl_create ../src/view-backend-exportable-fdo-egl.cpp:292
#2 0x7fe5aa59cc3f in WebKit::AcceleratedBackingStoreWayland::AcceleratedBackingStoreWayland(WebKit::WebPageProxy&) (libwebkit2gtk-4.0.so.37+0x4315c3f)
#3 0x7fe5aa59cd4a in WebKit::AcceleratedBackingStoreWayland::create(WebKit::WebPageProxy&) (libwebkit2gtk-4.0.so.37+0x4315d4a)
#4 0x7fe5aa59b854 in WebKit::AcceleratedBackingStore::create(WebKit::WebPageProxy&) …

Fix ClientBundle leak

---

src/initialize-shm.cpp

This is consistent with the wpe_fdo_initialize_for_egl_display API. Constructing
one instance per call would lead to wl_display leaks.
The SHM wl_display is now created once only, but remains alive during the
process life-time. A proper deinitialization API might be added later on in
order to give the application full control on the resources life-time.

shm: Construct the WS instance once only

---

include/wpe/exported-buffer-shm.h
include/wpe/exported-image-egl.h
include/wpe/extensions/audio.h
include/wpe/unstable/fdo-eglstream.h
include/wpe/unstable/fdo-shm.h
include/wpe/unstable/view-backend-exportable-eglstream.h
include/wpe/view-backend-exportable-egl.h
include/wpe/view-backend-exportable.h

Remove unneeded inclusions of libwpe headers, preferring forward declarations of the needed types and make all the inclusions use double quoted paths (to prefer local header versions, as opposed to installed ones).

Simplify public headers

---

src/view-backend-private.cpp
src/view-backend-private.h
src/ws.cpp

**DESCRIPTION:**
This MR fixes a crash in the WebKit UI-process. This crash happens when the wl_client of the related to a surface of a blocked content loaded request is being closed because an WL_EVENT_HANGUP (5).
In this scenario, the UI-process doesn't know about this client being closed and because it has its own copy of the wl_client pointer it keeps trying to operate over it during the release/dispatch actions. Therefore, the client is being freed in the wayland code when the error happens but the ViewBackend will never will know that its copy of the pointer is pointing to an area that it will be deleted.
The WL_EVENT_HANGUP happens immediately after that the content is blocked. If we are able to close the client and/or unregister the surface related to this request in a civilized …

view-backend-exportable-private: Add wl_client_add_destroy_listener in the ViewBackend

---

meson.build

Make the proect name lowercase, which allows using `meson dist` to create release tarballs named `wpebackend-fdo-<version>.tar.xz`. In order to keep built artifacts the same as before, stop using
`meson.project_name()` and use the `'WPEBackend-fdo'` string directly.

meson: Make "meson dist" usable for release tarballs

---

src/ipc.cpp
src/view-backend-private.cpp

I noticed that each time WebKit launches a new web process, the new process has two more sockets open than the previous one. This becomes severe when many web processes are in use simultaneously. In Epiphany, I can open roughly 70 tabs before other things start to go wrong, meaning 140 fds leaked into the final web process.
Turns out we are missing SOCK_CLOEXEC in ViewBackend::initialize, and so the sockets we create here remain open in the child process. Let's fix that.
But wait! Shouldn't the client fd be leaked to the web process? That's why it's created, after all: to allow the UI process to talk to the web process. So why is it OK to use CLOEXEC? Because the actual fd passed to the child process is not the one created in ViewBackend::initialize, but the one created using dup() in …

view-backend-exportable-private: use SOCK_CLOEXEC

---

src/ipc.cpp

Sometimes, on shutdown, we see "errors" like:
(WebKitWebProcess:2): WPE-FDO-WARNING **: 15:50:46.723: Failed to send message 67 to socket: Error sending data: Broken pipe
This is race is expected, so let's not clutter our logs with it.

ipc: silence warnings when peer closes its socket

---

include/wpe/version.h
include/wpe/wpebackend-fdo-version.h
meson.build
scripts/version.py
src/exported-image-egl.cpp
src/extensions/audio-receiver.cpp
src/extensions/audio.cpp
src/extensions/video-plane-display-dmabuf-receiver.cpp
src/extensions/video-plane-display-dmabuf.cpp
src/initialize-eglstream.cpp
src/initialize-shm.cpp
src/linux-dmabuf/linux-dmabuf.cpp
src/version.c
src/view-backend-exportable-fdo-egl.cpp
src/view-backend-exportable-fdo-eglstream.cpp
src/view-backend-exportable-fdo.cpp

Use a fixed `wpebackend-fdo-version.h` header which contains `#defines` for the version numbers only, which is the location where the canonical version is read by the build system, and also used by `version.h`, which does not need to be generated anymore.
This avoids needing to use relative `#include` paths, which continued being a pitfall even after the recent improvements due to the mixup of headers with the same name (and relative path!) in the preprocessor search path e.g. `wpe/version.h` from libwpe.
----
This follows the same principle as https://github.com/WebPlatformForEmbedded/libwpe/pull/76

Avoid generated version header

---

include/wpe/exported-buffer-shm.h
src/exported-buffer-shm.cpp

Add the wpe_fdo_shm_exported_buffer_get_resource() entrypoint,
allowing the recepient of the export to also access the wl_resource
object and using that to e.g. attach destroy listeners to that
resource object.

exported-buffer-shm.h: add a wl_resource getter

---

src/view-backend-private.cpp
src/ws.cpp

... and add an safeguard to avoid call it twice for the the same wl_client.
This patch is a rework over the original wl_client_destroy added in https://github.com/Igalia/WPEBackend-fdo/pull/127/commits/d086b69397f529ef175ce89909fe443e4f1393dd to avoid crashes like this in https://github.com/Igalia/WPEBackend-fdo/pull/127#discussion_r583508043
This new patch intends to address a new crash introduced by the previous change and identified in https://github.com/Igalia/WPEBackend-fdo/pull/127#discussion_r578492400. This new crash is caused by the unilateral destruction of the `wl_client` in the `Instance::unregisterViewBackend(uint32_t surfaceId)`.
The rationale behind this change is to ensure the `wl_client` is immediately destroyed when the `FdoIPC::Messages::UnregisterSurface` message is …

view-backend-private: Move wl_client_destroy to unregisterSurface()

---

src/view-backend-exportable-private.cpp
src/view-backend-exportable-private.h
src/ws.cpp

**Motivation:**
Backport of the following to Pull Requests from master to the wpebackend-fdo-1.8 branch: https://github.com/Igalia/WPEBackend-fdo/pull/127; https://github.com/Igalia/WPEBackend-fdo/pull/140
These 2 Pull Requests fix several crashes related to the ViewBackend destruction. Both crashes are vastly documented in the backlog of each Pull Request (PR).
**Detailed list of backported commits:** d688cd2558807c1ed15d67e5b0ecfad52a2bf90b;  d7577891d505a3fb037ec14e54568fe59e310941; 9e7dfbe7cbca8bc59c81d1e6421a527a87796880; 9a0e6cb62bfae44ef3496d950899ecb34ddd24a5; 87f032c8d34fe18060743ab60a6ca7f64e07f751

Backport to wpebackend-fdo 1.8: Safeguard access to destroyed wl_client

---

include/wpe/fdo-egl.h
include/wpe/fdo.h

Make `<wpe/fdo.h>` and `<wpe/fdo-egl.h>` include `<wpe/wpe.h>`, which is after all a dependency. Code that relied on the latter being automatically pulled in stopped building after #132, so modifying the top-level headers this way keeps the existing expectation.
Fixes #141

Include <wpe/wpe.h> from the top-level API headers

---

src/view-backend-private.cpp
src/view-backend-private.h

When a new surface is registered for an existing `ViewBackend`, unregister the old one first, to avoid keeping stale registrations. This makes the `WS::Instance::m_viewBackendMap` only contain one entry pointing for any given `ViewBackend` instance, instead of growing continuously.
To ensure that the same code path is taken when the `wl_client` for a `ViewBackend` is destroyed, all the operations to be done are moved into `ViewBackend::clientDestroyNotify()`, the callback of the `wl_client` destruction listener, then `ViewBackend::unregisterSurface()` only needs to call `wl_client_destroy()`. This way the `~ViewBackend` destructor only needs to call `unregisterSurface()` as well.
Also, avoid doing any operation in `ViewBackend::dispatchFrameCallbacks()` and `ViewBackend::releaseBuffer()` …

view backend: Properly unregister surfaces

---

src/extensions/audio.cpp
src/extensions/video-plane-display-dmabuf.cpp
src/ws-client.cpp

If we fail to bind any global objects, we are going to crash. Let's do
that as nicely as possible using g_error(), rather than dereferencing
null pointers later on.
Suggested by #145

Add some checks to ensure we properly bind server globals

---

src/view-backend-private.cpp
src/view-backend-private.h
src/ws.cpp
src/ws.h

This has two commits with changes that (IMO) make the code a tad easier to follow:
* The `Surface::id` and `Surface::client` members can both be replaced by keeping around the  `wl_resource`, and query its client with `wl_resource_get_client()`; the identifier itself is never used—and if ever needed, there is `wl_resource_get_id()` which could be used.
* The `WS::Singleton::m_viewBackendMap` associated an identifier generated by the `wpe_bridge` interface with a given `Surface`, hence using “surfaceId” around is misleading and changing variables to use “bridgeId” seems more appropriate.

A couple of wpe_bridge related cleanups

---

src/view-backend-private.cpp
src/view-backend-private.h
src/ws.cpp
src/ws.h

Move code around to accumulate surface frame callback additions until changes are comitted to the surface, as intended according to the base Wayland protocol specification.
As a bonus, remove the auxiliar `ViewBackend::FrameCallbackResource` by passing a destruction callback to `wl_resource_set_implementation()` and using the internal `wl_resource` list link.

ws: Accumulate surface frame callbacks until commit

---

.github/workflows/ci.yml
scripts/version.py

In theory we support building with Python as old as 3.5, but the CI was using 3.6. This downgrades the version used when doing test builds, and fixes an issue in the `scripts/version.py` helper script.

Meson: Fix the build with Python 3.5

---

src/ws.cpp
src/ws.h

... of the create surface method of the `struct wl_compositor_interface`
This commits prevents crashes by accessing to already deleted Surfaces destroyed by a premature wl_client_destroy method call. For example, trying to load a non-allowed URI filtered by a Content-Filter policy.
Changes:
* The Instance class implements an Instance::unregisterSurface().
* The destroy callback in the wl_resource_set_implementation for the created Surface now includes a Instance::unregisterSurface(). For this removes the surface from the ViewBackendMap avoiding dispatch operations over a already destroyed Surface.
* The Instance::dispatchFrameCallbacks(uint32_t bridgeId) still checks if the bridgeId has an associated Surface in the ViewBackendMap but now just  logs a warning message and avoids to fail …

Add Instance::unregisterSurface() in the destroy funct 

---

src/view-backend-private.cpp
src/view-backend-private.h
src/ws.cpp
src/ws.h

Instead of trying to keep track of the destruction of the `wl_client` referenced by `ViewBackend::m_client`, completely remove the member variable and instead:
- In `ViewBackend::releaseBuffer()` use `wl_resource_get_client()` to obtain the `wl_client` from the buffer resource. Given that the buffer resource has just been used, it is guaranteed that the `wl_client` it refers to should be still valid.
- In `ViewBackend::dispatchFrameCallbacks()` remove the flush call, and instead do it in `WS::Surface::dispatchFrameCallbacks()`, and pick the `wl_client` from the callback resource objects, if any callback was dispatched at all. Again, if any callback was dispatched their associated `wl_client` should be still valid. Skipping the flush if no callbacks are dispatched is fine because in that …

ws: Remove wl_client pointer that can end up dangling

---

src/extensions/audio.cpp
src/extensions/video-plane-display-dmabuf.cpp

Remove wrong `NULL` checks for variables which are actually allowed to be `NULL` during normal operation.
The global objects for the `wpe_audio` and `wpe_video_plane_display_dmabuf` interfaces are created dynamically when a receiver is registered for them, which means at the time the nested compositor client is connected they may be `NULL`.

Partially revert a4eb79d, video-plane and audio can be NULL

---

meson.build

Try finding the wayland-scanner program first without involving picking its path from the `pkg-config` dependency. This way it is possible to instruct Meson to override the the path where to find it using the `[binaries]` section of a [native file](https://mesonbuild.com/Machine-files.html) during cross-compilation.

meson: Try wayland-scanner first without pkg-config

---

src/view-backend-private.cpp
src/view-backend-private.h
src/ws.cpp
src/ws.h

As each ViewBackend (and hence web view) can get its contents rendered by different WPEWebProcess due to PSON, keep around a list of all the differen bridgeIds which have been associated with it in a `std::vector`. Newly added elements are always pushed at the back, so the most recent association (i.e. the “current” active one) is always the last element. Keeping the list allows getting back to the previously used ones.
----
Fixes #155
Note that this may need some testing with the `devel/multiple-views` and under WebKitGTK before merging.
This is an alternative to #156 which implements a general solution.

Keep list of bridgeIds associated with each ViewBackend

---

meson.build

Add the missing `cpp_rtti=false` option in the list of defaults, which will be picked by Meson 0.53 or newer. Older versions will keep using the existing check.

meson: Add cpp_rtti=false default option

---

src/ws.cpp

Do not use values from an iterator after the element it refers to has been erased from a container, to avoid falling in the pit of undefined behaviour.
Fixes #162

ws: Avoid using a field of an erased iterator

---

include/wpe/unstable/dmabuf-pool-entry.h
include/wpe/unstable/fdo-dmabuf.h
include/wpe/unstable/initialize-dmabuf.h
include/wpe/unstable/view-backend-dmabuf-pool-fdo.h
meson.build
src/bridge/wpe-bridge.xml
src/dmabuf-pool-entry-private.h
src/dmabuf-pool-entry.cpp
src/dmabuf-pool/wpe-dmabuf-pool.xml
src/egl-client-dmabuf-pool.cpp
src/egl-client-dmabuf-pool.h
src/egl-client.h
src/initialize-dmabuf.cpp
src/renderer-backend-egl.cpp
src/view-backend-dmabuf-pool-fdo.cpp
src/view-backend-exportable-fdo-egl.cpp
src/view-backend-exportable-fdo-eglstream.cpp
src/view-backend-exportable-fdo.cpp
src/view-backend-private.cpp
src/view-backend-private.h
src/ws-client.cpp
src/ws-client.h
src/ws-dmabuf-pool.cpp
src/ws-dmabuf-pool.h
src/ws-egl.h
src/ws-eglstream.h
src/ws-shm.h
src/ws-types.h
src/ws.cpp
src/ws.h

Introduce wpe_view_backend_dmabuf_pool_fdo, a wpe_view_backend extension that
demands manual dmabuf managemenet from the user.
This approach to buffer management allows for most flexibility in terms of what
kind of dmabuf objects should be used for rendering. It allows for user to
specify in detail the format, multi-planarity and modifier data of the dmabuf
object.
In order to work with such dmabuf objects, the renderer_backend_egl interfaces
have to leverage a new WS::EGLClient implementation that uses custom Wayland
protocols to properly handle dmabuf content across process boundaries. To
correctly render into these objects, we have to leverage the surfaceless EGL
platform, along with importing the dmabuf objects into EGLImages that we then
use as backing resources for renderbuffers …

Add unstable dmabuf-pool API

---

meson.build
scripts/version.py

meson: Use implicit dependencies for required dependencies.
The generated pkgconfig file for the library is incomplete, since application,
such as cog, only explicity depend on WPEBackend-fdo, though it also depends on
libwpe. It has not been a problem since wpe-webkit-1.0.pc explicity expose
libwpe requirement. Still, for robustness and self documentation, it's better to
express that dependency explicity too.
Also, this patch removes the pkg config version declation since it's also
handled implicitly by meson.
Previous pc file:
prefix=/usr
libdir=${prefix}/lib/x86_64-linux-gnu
includedir=${prefix}/include
Name: wpebackend-fdo-1.0
Description: The WPEBackend-fdo library
Version: 1.9.91
Libs: -L${libdir} -lWPEBackend-fdo-1.0
Cflags: -I${includedir}/wpe-fdo-1.0
New pc file: …

Meson updates

---

src/view-backend-exportable-fdo-egl.cpp

Detected this SIGSEGV when trying to login to game stores in Lutris.
May fix #175 
Also fixes crashes in Epiphany, and possibly in other WebKit2 applications as well.

Fix SIGSEGV in WebKit2 applications

---

.github/workflows/ci.yml

Run the Clang static analyzer as a CI job. Instead of using `scan-build`, which uses `LD_PRELOAD` to interpose the compiler, install the Python scan-build package which includes an `analyze-build` program that can directly ingest the JSON compilation database.

CI: Add task to run the Clang static analyzer

---

.github/workflows/ci.yml

Switch to Ubuntu 20.04LTS, which is the oldest currently supported, and Python to 3.6 which is the lowest available for 20.04. Bump the Meson dependency to 0.55, because libwpe has started requiring it.
Update to the latest versions of the GitHub Actions, while at it.

CI: Update component versions

---

src/ws-egl.cpp

With this specific version of NVidia drivers, modifiers cannot be queried for specific formats, so instead of raising an assertion let's just ignore the format silently.

Fix assert for NVidia drivers 525.60.11

---

src/view-backend-exportable-fdo-egl-private.h
src/view-backend-exportable-fdo-egl.cpp

view-backend-exportable-fdo-egl.cpp relies on the bufferDestroyListenerCallback for destroying the image, This is called during the wl_resource_destroy() to release the image.
Related-to: #175 #176

Remove image on buffer destroy callback only

---

meson.build

Update to Meson 0.52.1, which should be available in all supported systems. This allows removing a workaround for documentation as the new Meson version includes a fixed HotDoc module.
----
Meson fix included in 0.52.1 and newer: https://github.com/mesonbuild/meson/pull/6163

meson: Require version 0.52.1, remove docs workaround

---

include/wpe/exported-image-egl.h

...because some documentation is always better than no documentation.

doc: Document EGL exported images

---

src/egl-client-wayland.cpp

In order to avoid off build failures due to mismatching (but compatible) declarations of `wl_egl_window` and `EGLNativeWindowType`, add an explicit cast to EGLNativeWindowType inside the `TargetWayland::nativeWindow()` function.
Solves the following build issue found by the Buildroot autobuilders:
- http://autobuild.buildroot.net/results/92c5cc3134e92c263a0cbb4c05ef8956569e434b/

Cast to EGLNativeWindowType explicitly

---

src/ws-client.cpp

Fixes wayland library warning on exit:
```
warning: queue 0x887860 destroyed while proxies still attached:
wpe_dmabuf_pool@12 still attached
```

Fix wpe_dmabuf_pool object leak

---

.github/workflows/ci.yml

The 18.04 runners are not available anymore as per https://github.com/actions/virtual-environments/issues/6002 so use instead the lowest available version at the moment.

CI: Run on Ubuntu 20.04

---

meson.build

Set the "check" parameter in run_command() calls, instead of relying on the default value, which might get changed at some point in the future.
This silences the following Meson warning:
```
WARNING: You should add the boolean check kwarg to the run_command call.
It currently defaults to false,
but it will default to true in future releases of meson.
See also: https://github.com/mesonbuild/meson/issues/9300
```

meson: Explicitly set run_command() check parameter

---

src/ipc.h

Without this the build fails with the upcoming gcc 15:
In file included from ../wpebackend-fdo-1.14.2/src/ipc.cpp:26: ../wpebackend-fdo-1.14.2/src/ipc.h:36:36: error: 'uint32_t' has not been declared
36 |     virtual void didReceiveMessage(uint32_t messageId, uint32_t messageBody) = 0

src/ipc.h: Include <stdint.h> for uint32_t

---

.github/workflows/ci.yml

Update to v4 of the upload-artifact GitHub action. The newer version is faster, and v3 is going to be deprecated next November:
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

CI: Update to use actions/upload-artifact v4
